language: java
jdk: oraclejdk11
addons:
  sonarcloud:
    organization: "diegomoronha"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DiegoMoronha_desapp-unq-grupo-J-022021

before_install:
  - chmod +x mvnw